import Database from 'better-sqlite3'
import path from 'path'
import fs from 'fs'

const DB_DIR = path.resolve(__dirname, '..', 'data')
if (!fs.existsSync(DB_DIR)) fs.mkdirSync(DB_DIR, { recursive: true })

const db = new Database(path.join(DB_DIR, 'activities.db'))
db.pragma('journal_mode = WAL')

db.exec(`
  CREATE TABLE IF NOT EXISTS activities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    provider TEXT NOT NULL,
    type TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT NOT NULL,
    cost TEXT NOT NULL,
    modality TEXT NOT NULL,
    level TEXT NOT NULL,
    tags TEXT NOT NULL,
    eligibility TEXT NOT NULL,
    location TEXT NOT NULL,
    freshness TEXT NOT NULL
  )
`)

db.exec('DELETE FROM activities')

const activities = [
  {
    title: "Machine Learning Specialization",
    provider: "Coursera / DeepLearning.AI",
    type: "course",
    url: "https://www.coursera.org/specializations/machine-learning-introduction",
    description: "Foundational ML program covering supervised learning, unsupervised learning, and best ML practices. Taught by Andrew Ng.",
    cost: "free to audit",
    modality: "online",
    level: "beginner",
    tags: "machine learning, python, ai, data science, career",
    eligibility: "all",
    location: "Remote",
    freshness: "2025-01-01",
  },
  {
    title: "Google Data Analytics Certificate",
    provider: "Coursera / Google",
    type: "certificate",
    url: "https://www.coursera.org/professional-certificates/google-data-analytics",
    description: "Professional certificate covering SQL, R, and Tableau. Designed for career changers seeking data roles.",
    cost: "paid (financial aid available)",
    modality: "online",
    level: "beginner",
    tags: "data analytics, sql, tableau, career, certificate",
    eligibility: "all",
    location: "Remote",
    freshness: "2025-01-01",
  },
  {
    title: "CS50: Introduction to Computer Science",
    provider: "Harvard / edX",
    type: "course",
    url: "https://cs50.harvard.edu/x/",
    description: "Harvard's intro to CS. Covers C, Python, SQL, HTML/CSS/JS. Free to complete, paid certificate available.",
    cost: "free to audit",
    modality: "online",
    level: "beginner",
    tags: "computer science, python, programming, career",
    eligibility: "all",
    location: "Remote",
    freshness: "2025-01-01",
  },
  {
    title: "MLH Fellowship",
    provider: "Major League Hacking",
    type: "community",
    url: "https://fellowship.mlh.io/",
    description: "12-week remote internship alternative contributing to open source projects. Stipend provided to selected fellows.",
    cost: "free (stipend)",
    modality: "online",
    level: "intermediate",
    tags: "open source, software engineering, fellowship, career, college",
    eligibility: "college",
    location: "Remote",
    freshness: "2025-03-01",
  },
  {
    title: "AI Community of Practice — US Government",
    provider: "Digital.gov",
    type: "community",
    url: "https://digital.gov/communities/artificial-intelligence/",
    description: "Federal community of practice for AI in government. Monthly calls, resources, and networking for AI practitioners.",
    cost: "free",
    modality: "online",
    level: "all",
    tags: "ai, networking, government, policy, community",
    eligibility: "professional",
    location: "Remote",
    freshness: "2025-01-01",
  },
  {
    title: "HackMIT",
    provider: "MIT",
    type: "hackathon",
    url: "https://hackmit.org/",
    description: "Annual MIT hackathon with 1000+ students building projects over a weekend. Travel reimbursement available.",
    cost: "free",
    modality: "in-person",
    level: "all",
    tags: "hackathon, networking, software engineering, college, projects",
    eligibility: "college",
    location: "Cambridge, MA",
    freshness: "2025-06-01",
  },
  {
    title: "AWS Cloud Practitioner Certification",
    provider: "Amazon Web Services",
    type: "certificate",
    url: "https://aws.amazon.com/certification/certified-cloud-practitioner/",
    description: "Entry-level cloud cert validating foundational AWS knowledge. Widely recognized by employers for cloud and devops roles.",
    cost: "paid ($100 exam)",
    modality: "online",
    level: "beginner",
    tags: "cloud, aws, certificate, career, devops",
    eligibility: "all",
    location: "Remote",
    freshness: "2025-01-01",
  },
  {
    title: "Full Stack Open",
    provider: "University of Helsinki",
    type: "course",
    url: "https://fullstackopen.com/en/",
    description: "Free deep dive into modern web development: React, Node.js, TypeScript, GraphQL. Free certificate from University of Helsinki.",
    cost: "free",
    modality: "online",
    level: "intermediate",
    tags: "web development, react, javascript, typescript, full stack",
    eligibility: "all",
    location: "Remote",
    freshness: "2025-01-01",
  },
  {
    title: "Y Combinator Startup School",
    provider: "Y Combinator",
    type: "course",
    url: "https://www.startupschool.org/",
    description: "Free 8-week online program on building startups from YC partners. Access to YC community and office hours.",
    cost: "free",
    modality: "online",
    level: "all",
    tags: "startup, entrepreneurship, business, yc, founder",
    eligibility: "all",
    location: "Remote",
    freshness: "2025-01-01",
  },
  {
    title: "TreeHacks",
    provider: "Stanford University",
    type: "hackathon",
    url: "https://treehacks.com/",
    description: "Stanford's flagship hackathon focused on high-impact tech. Travel grants available for admitted students.",
    cost: "free",
    modality: "in-person",
    level: "all",
    tags: "hackathon, stanford, ai, software engineering, college",
    eligibility: "college",
    location: "Stanford, CA",
    freshness: "2025-06-01",
  },
  {
    title: "Google Summer of Code",
    provider: "Google",
    type: "volunteering",
    url: "https://summerofcode.withgoogle.com/",
    description: "Paid open source internship. Contribute to open source orgs over summer with a stipend from Google.",
    cost: "free (stipend $1500–$6600)",
    modality: "online",
    level: "intermediate",
    tags: "open source, software engineering, google, internship, stipend",
    eligibility: "college",
    location: "Remote",
    freshness: "2025-03-01",
  },
  {
    title: "Taproot Foundation Pro Bono Volunteering",
    provider: "Taproot Foundation",
    type: "volunteering",
    url: "https://taprootplus.org/",
    description: "Pro bono professional services platform connecting skilled volunteers with nonprofits. Real-world portfolio building.",
    cost: "free",
    modality: "online",
    level: "intermediate",
    tags: "volunteering, nonprofit, professional skills, portfolio, career",
    eligibility: "professional",
    location: "Remote",
    freshness: "2025-01-01",
  },
  {
    title: "IEEE Student Membership",
    provider: "IEEE",
    type: "professional association",
    url: "https://www.ieee.org/membership/students/index.html",
    description: "Global professional network for engineering students with publications, conferences, and local chapter events.",
    cost: "paid ($32/year)",
    modality: "hybrid",
    level: "all",
    tags: "engineering, networking, professional, conferences, college",
    eligibility: "college",
    location: "US",
    freshness: "2025-01-01",
  },
  {
    title: "AI Safety Fundamentals",
    provider: "BlueDot Impact",
    type: "course",
    url: "https://aisafetyfundamentals.com/",
    description: "8-week cohort course on AI safety and alignment. Covers technical and governance aspects. Free reading groups available.",
    cost: "free",
    modality: "online",
    level: "intermediate",
    tags: "ai safety, alignment, policy, research, ai, governance",
    eligibility: "all",
    location: "Remote",
    freshness: "2025-01-01",
  },
  {
    title: "Kaggle Competitions",
    provider: "Kaggle / Google",
    type: "community",
    url: "https://www.kaggle.com/competitions",
    description: "Data science competitions with real datasets and cash prizes. Strong portfolio-building opportunity with a large community.",
    cost: "free",
    modality: "online",
    level: "all",
    tags: "data science, machine learning, competition, portfolio, python",
    eligibility: "all",
    location: "Remote",
    freshness: "2025-03-01",
  },
  {
    title: "Buildspace Nights & Weekends",
    provider: "Buildspace",
    type: "community",
    url: "https://buildspace.so/",
    description: "6-week cohort to build and ship your own project alongside thousands of builders worldwide. Strong community.",
    cost: "free",
    modality: "online",
    level: "all",
    tags: "startup, building, community, projects, entrepreneurship",
    eligibility: "all",
    location: "Remote",
    freshness: "2025-01-01",
  },
  {
    title: "PennApps",
    provider: "University of Pennsylvania",
    type: "hackathon",
    url: "https://pennapps.com/",
    description: "One of the oldest collegiate hackathons. 1200+ participants, $20k+ in prizes, and a strong alumni network.",
    cost: "free",
    modality: "in-person",
    level: "all",
    tags: "hackathon, college, software engineering, prizes, networking",
    eligibility: "college",
    location: "Philadelphia, PA",
    freshness: "2025-06-01",
  },
  {
    title: "LinkedIn Learning Business & Tech Courses",
    provider: "LinkedIn Learning",
    type: "course",
    url: "https://www.linkedin.com/learning/",
    description: "Extensive library of business and tech courses. Often free through public libraries. Certificates display on LinkedIn profile.",
    cost: "free (with library card)",
    modality: "online",
    level: "all",
    tags: "business, leadership, communication, professional, career",
    eligibility: "all",
    location: "Remote",
    freshness: "2025-01-01",
  },
  {
    title: "PMP Certification",
    provider: "Project Management Institute",
    type: "certificate",
    url: "https://www.pmi.org/certifications/project-management-pmp",
    description: "Gold standard project management certification. Globally recognized for professionals leading teams and projects.",
    cost: "paid ($405 members / $555 non-members)",
    modality: "hybrid",
    level: "advanced",
    tags: "project management, pmp, leadership, professional, certification",
    eligibility: "professional",
    location: "US",
    freshness: "2025-01-01",
  },
  {
    title: "Dev.to Community",
    provider: "DEV Community",
    type: "community",
    url: "https://dev.to/",
    description: "Online community of software developers sharing articles, discussions, and projects. Great for building a public profile.",
    cost: "free",
    modality: "online",
    level: "all",
    tags: "software engineering, community, writing, portfolio, career",
    eligibility: "all",
    location: "Remote",
    freshness: "2025-01-01",
  },
  {
    title: "Responsible AI Certification",
    provider: "Responsible AI Institute",
    type: "certificate",
    url: "https://www.responsible.ai/certification/",
    description: "Professional cert in responsible AI practices: ethics, bias, governance, and compliance frameworks.",
    cost: "paid",
    modality: "online",
    level: "intermediate",
    tags: "ai ethics, responsible ai, governance, professional, policy",
    eligibility: "professional",
    location: "Remote",
    freshness: "2025-01-01",
  },
  {
    title: "Product Management Fellowship",
    provider: "Exponent",
    type: "community",
    url: "https://www.tryexponent.com/",
    description: "Community and program helping aspiring PMs break into product management through mock interviews and resources.",
    cost: "paid (subscription)",
    modality: "online",
    level: "intermediate",
    tags: "product management, pm, career, interview, business",
    eligibility: "all",
    location: "Remote",
    freshness: "2025-01-01",
  },
  {
    title: "HackNY",
    provider: "hackNY",
    type: "hackathon",
    url: "https://hackny.org/",
    description: "NYC's premier student hackathon with mentorship from the NYC tech ecosystem. Focused on social good applications.",
    cost: "free",
    modality: "in-person",
    level: "all",
    tags: "hackathon, nyc, social good, software engineering, college",
    eligibility: "college",
    location: "New York, NY",
    freshness: "2025-06-01",
  },
  {
    title: "Data Science DC Meetup",
    provider: "Meetup.com / Data Science DC",
    type: "meetup",
    url: "https://www.meetup.com/data-science-dc/",
    description: "Monthly in-person meetups on data science topics. One of the largest DS communities on the East Coast.",
    cost: "free",
    modality: "in-person",
    level: "all",
    tags: "data science, networking, meetup, community, machine learning",
    eligibility: "all",
    location: "Washington, DC",
    freshness: "2025-03-01",
  },
  {
    title: "Tech Elevator Coding Bootcamp",
    provider: "Tech Elevator",
    type: "course",
    url: "https://www.techelevator.com/",
    description: "14-week intensive coding bootcamp with job placement support. Focus on Java or .NET full-stack development.",
    cost: "paid ($15,950 — ISA available)",
    modality: "hybrid",
    level: "beginner",
    tags: "coding bootcamp, software engineering, job placement, career change",
    eligibility: "all",
    location: "US",
    freshness: "2025-01-01",
  },
]

const insert = db.prepare(`
  INSERT INTO activities (title, provider, type, url, description, cost, modality, level, tags, eligibility, location, freshness)
  VALUES (@title, @provider, @type, @url, @description, @cost, @modality, @level, @tags, @eligibility, @location, @freshness)
`)

const insertMany = db.transaction((acts: typeof activities) => {
  for (const act of acts) insert.run(act)
})

insertMany(activities)
console.log(`✓ Seeded ${activities.length} activities`)
db.close()
